### ISSUE TITLE
Checksum issue creates useless patched JAR (with a smaller filesize)

### ISSUE THREAD

**Issue by toydotgame** [NepNep21/MSA4Legacy#3]
## Info
**Launch Command:** `java -jar launcher-1.0.0.jar > output.log`, run in directory `/home/user/Downloads/launcher/`
### `/home/user/Downloads/launcher/` File Tree
* `launcher.jar` (4.3 MiB)
* `patches.lzma`
* `installer-1.0.0.jar`
(After run:)
* `launcher-patched.jar` (219.9 KiB)
* `output.log`

### `pacman -Q java-openjfx jre-openjdk jre8-openjdk`
```
java-openjfx 17.0.0.1.u1-1
jre-openjdk 17.0.1.u12-1
jre8-openjdk 8.u312-2
```

### `archlinux-java status`
```
Available Java environments:
  java-11-openjdk
  java-17-openjdk
  java-7-openjdk/jre
  java-8-openjdk/jre (default)
```

### `uname -r`
```
5.16.5-arch1-1
```

## \[Start of\] Stack Trace
```
java.io.IOException: Patch expected net/minecraft/launcher/updater/CompleteMinecraftVersion to have the checksum 74c8a9d but it was eea83fd
	at net.minecraftforge.binarypatcher.Patcher.patch(Patcher.java:197)
	at net.minecraftforge.binarypatcher.Patcher.process(Patcher.java:149)
	at net.minecraftforge.binarypatcher.ConsoleTool.main(ConsoleTool.java:161)
	at me.nepnep.msa4legacy.installer.Main$1$1.actionPerformed(Main.java:29)
```
**Full output at:** [pastebin.com/tLck8jEt](https://pastebin.com/raw/tLck8jEt) (Almost 5,000 lines)

***

## Description
I can only think that a checksum error is because of the version of the launcher I'm using. I got it from [this Stack Exchange answer](https://gaming.stackexchange.com/a/378349), which gave this link:
[launcher.mojang.com/mc/launcher/jar/fa896bd4c79d4e9f0d18df43151b549f865a3db6/launcher.jar.lzma](http://launcher.mojang.com/mc/launcher/jar/fa896bd4c79d4e9f0d18df43151b549f865a3db6/launcher.jar.lzma)
I lost the original YouTube tutorial I used to get my legacy launcher from. One thing I have noticed is that the usual red text I had at the top of the launcher (saying that it was outdated) isn't there. I think it may be an older launcher version.
<br>
Where do I find the right version? (And if this _is_ the cause of my issue, shouldn't there be a note in the README detailing version dependency?)

Do I need to provide any other information?

**Comment by toydotgame** [comment]
Thanks. That seems to have got the launcher working. It patches correctly and with no errors.
Also, not to be a pain, _but,_ I'm now getting another stack trace:
```
[16:59:50 ERROR]: Unexpected exception refreshing profile list
java.lang.NullPointerException
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:182) [launcher-patched.jar:1.6.93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[16:59:50 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel.populateProfiles(ProfileSelectionPanel.java:90) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.ui.bottombar.ProfileSelectionPanel$1.run(ProfileSelectionPanel.java:84) ~[launcher-patched.jar:1.6.93]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_312]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_312]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_312]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_312]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_312]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_312]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_312]
[16:59:50 ERROR]: Unhandled exception in executor com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask@253cd585
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
	at com.mojang.launcher.updater.ExceptionalThreadPoolExecutor$ExceptionalFutureTask.done(ExceptionalThreadPoolExecutor.java:72) [launcher-patched.jar:1.6.93]
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:384) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.setException(FutureTask.java:251) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:271) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:70) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:189) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.Launcher.ensureLoggedIn(Launcher.java:238) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.Launcher$2.run(Launcher.java:210) ~[launcher-patched.jar:1.6.93]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	... 3 more
```
Pressing the _Switch User_ button prints this trace every press, too:
```
[17:01:02 FATAL]: Unhandled exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at net.minecraft.launcher.profile.ProfileManager.saveProfiles(ProfileManager.java:70) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.SwingUserInterface.showLoginPrompt(SwingUserInterface.java:189) ~[launcher-patched.jar:1.6.93]
	at net.minecraft.launcher.ui.bottombar.PlayerInfoPanel$1.actionPerformed(PlayerInfoPanel.java:49) ~[launcher-patched.jar:1.6.93]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_312]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_312]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_312]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_312]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_312]
	at java.awt.Component.processMouseEvent(Component.java:6539) ~[?:1.8.0_312]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_312]
	at java.awt.Component.processEvent(Component.java:6304) ~[?:1.8.0_312]
	at java.awt.Container.processEvent(Container.java:2239) ~[?:1.8.0_312]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_312]
	at java.awt.Container.dispatchEventImpl(Container.java:2297) ~[?:1.8.0_312]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_312]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) ~[?:1.8.0_312]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) ~[?:1.8.0_312]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) ~[?:1.8.0_312]
	at java.awt.Container.dispatchEventImpl(Container.java:2283) ~[?:1.8.0_312]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_312]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_312]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) ~[?:1.8.0_312]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_312]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_312]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_312]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) ~[?:1.8.0_312]
	at java.awt.EventQueue$4.run(EventQueue.java:733) ~[?:1.8.0_312]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_312]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_312]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) ~[?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_312]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_312]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_312]
```
![image](https://user-images.githubusercontent.com/64190512/154009476-51babdb8-81ab-4448-a4f6-db6a2f0b3530.png)

I don't know what error this is. I _think_ it's to do with `net.minecraft.launcher.SwingUserInterface.showLoginPrompt`? Any ideas?

**Comment by NepNep21** [comment]
That is likely caused by having files from the new launcher in .minecraft, you can either delete those (but keeping a backup of course) or change this one's working directory with the `--workDir` argument

**Comment by toydotgame** [comment]
I specified `--workDir .`, and everything loads fine, but now there's a HTTP 401 when I press _Log In_. I authorised `NepAuth` in my browser and all, but after I finished that and M$ said I could close the tab, nothing changed in the client. I tried relaunching, re-entering my e-mail, and pressing _Log In_ – same error.
![image](https://user-images.githubusercontent.com/64190512/154153404-f9927d2f-3527-4cc1-a3c9-25a485725b5e.png)
[Stack trace](https://pastebin.com/raw/RC7w46B9)

Should I close this issue while I work through these other errors, given that AFAIK they're unrelated?

**Comment by NepNep21** [comment]
Ah i see, i don't know what error you're getting but i do know why it isn't showing, i put the 401 check and the extra logging that allows after the getInputStream call, so it never runs, i'll fix that so you can send a new stacktrace with the info that gives

**Comment by NepNep21** [comment]
Update once the action for the commit i just pushed finishes running and send the new stacktrace

**Comment by toydotgame** [comment]
Ah sorry, only saw this notification now.

***

Re-M$-authenticated,
![image](https://user-images.githubusercontent.com/64190512/154211471-6fccbc5a-898f-4870-a3de-4ccf65f24b12.png)
then after a few seconds:
```
[16:49:31 ERROR]: Failed to authenticate
me.nepnep.msa4legacy.patches.MicrosoftAuth$XErrException: XSTS auth returned 401 with XErr 2148916238
	at me.nepnep.msa4legacy.patches.MicrosoftAuth.xstsAuth(MicrosoftAuth.java:167) ~[launcher-patched.jar:1.6.93]
	at me.nepnep.msa4legacy.patches.MicrosoftAuth.access$200(MicrosoftAuth.java:34) ~[launcher-patched.jar:1.6.93]
	at me.nepnep.msa4legacy.patches.MicrosoftAuth$2.apply(MicrosoftAuth.java:75) [launcher-patched.jar:1.6.93]
	at me.nepnep.msa4legacy.patches.MicrosoftAuth$2.apply(MicrosoftAuth.java:57) [launcher-patched.jar:1.6.93]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_312]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_312]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_312]
```
(Also happens on _Log In_ button press)

**Comment by toydotgame** [comment]
Ah! There ya go! Made myself younger by five years, waited 10 minutes, and deleted `microsoft_accounts.json`, and I'm good.
![image](https://user-images.githubusercontent.com/64190512/154214994-52b9894b-f3f2-4ba8-9ce4-975df5c44b2c.png)
