### ISSUE TITLE
Cannot launch the game

### ISSUE THREAD

**Issue by sticks-stuff** [NepNep21/MSA4Legacy#6]
```
[22:38:44 FATAL]: Unhandled exception in thread Thread[pool-2-thread-3,5,main]
java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.lang.ThreadLocal.threadLocalHashCode accessible: module java.base does not "opens java.lang" to unnamed module @4df828d7
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:116) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.RemoteVersionList.getCompleteVersion(RemoteVersionList.java:41) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:223) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.MinecraftVersionManager.getLatestCompleteVersion(MinecraftVersionManager.java:53) ~[launcher-patched.jar:1.6.93]
        at com.mojang.launcher.game.runner.AbstractGameRunner.playGame(AbstractGameRunner.java:76) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.game.GameLaunchDispatcher$1.run(GameLaunchDispatcher.java:127) ~[launcher-patched.jar:1.6.93]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

It also can't seem to load any version of Minecraft

```
[22:38:22 ERROR]: Couldn't load local version C:\Users\stick\AppData\Roaming\.minecraft\versions\1.8.9\1.8.9.json
java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.lang.ThreadLocal.threadLocalHashCode accessible: module java.base does not "opens java.lang" to unnamed module @4df828d7
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[?:?]
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:116) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.getAdapter(Gson.java:356) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.LocalVersionList.refreshVersions(LocalVersionList.java:58) [launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.MinecraftVersionManager.refreshVersions(MinecraftVersionManager.java:80) [launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.Launcher$2.run(Launcher.java:175) [launcher-patched.jar:1.6.93]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by NepNep21** [comment]
It's possible the launcher is incompatible with newer java versions, try running it with java 8 (must have javafx too)

**Comment by sticks-stuff** [comment]
That works, though as expected anything newer than (whatever minecraft version starts requiring java 8) doesn't work.
For reference, the version of Java I used for Windows is https://cdn.azul.com/zulu/bin/zulu8.64.0.19-ca-fx-jre8.0.345-win_x64.zip

On an unrelated note, I actually can't test what versions work and what don't because I can't seem to log in anymore lol

```
[14:38:36 ERROR]: Failed to authenticate
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.minecraftservices.com/authentication/login_with_xbox
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1917) ~[?:1.8.0_345]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505) ~[?:1.8.0_345]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_345]
        at me.nepnep.msa4legacy.patches.MicrosoftAuth.minecraftAuth(MicrosoftAuth.java:193) ~[launcher-patched.jar:1.6.93]
        at me.nepnep.msa4legacy.patches.MicrosoftAuth.access$300(MicrosoftAuth.java:34) ~[launcher-patched.jar:1.6.93]
        at me.nepnep.msa4legacy.patches.MicrosoftAuth$2.apply(MicrosoftAuth.java:76) [launcher-patched.jar:1.6.93]
        at me.nepnep.msa4legacy.patches.MicrosoftAuth$2.apply(MicrosoftAuth.java:57) [launcher-patched.jar:1.6.93]
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) [?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) [?:1.8.0_345]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_345]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_345]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_345]
```

At the same time I started being unable to log in, this error started popping up for every version too, no idea if thats related

```
[13:54:44 ERROR]: Couldn't load local version C:\Users\stick\AppData\Roaming\.minecraft\versions\1.8.9\1.8.9.json
java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.google.gson.TypeAdapterFactory. Register an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:210) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:162) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.LocalVersionList.refreshVersions(LocalVersionList.java:58) [launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.updater.MinecraftVersionManager.refreshVersions(MinecraftVersionManager.java:80) [launcher-patched.jar:1.6.93]
        at net.minecraft.launcher.Launcher$2.run(Launcher.java:175) [launcher-patched.jar:1.6.93]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_345]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_345]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_345]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_345]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207) ~[launcher-patched.jar:1.6.93]
        ... 20 more
Caused by: java.lang.InstantiationException: com.google.gson.TypeAdapterFactory
        at sun.misc.Unsafe.allocateInstance(Native Method) ~[?:1.8.0_345]
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_345]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_345]
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:48) ~[launcher-patched.jar:1.6.93]
        at com.google.gson.internal.ConstructorConstructor$12.construct(ConstructorConstructor.java:207) ~[launcher-patched.jar:1.6.93]
        ... 20 more
```

**Comment by NepNep21** [comment]
The auth error should be a one time bug, make sure nothing else is trying to log you in to be safe
About versions requiring a newer java version than 8, you can set the jre for running the game on a per instance basis in the settings
And about the gson error, that is probably caused by new launcher settings not being compatible with the old launcher, you can set another mc directory in as a command line argument (which i can further help with in a few hours if you want, just say it) or move/delete the new launcher files

**Comment by NepNep21** [comment]
Is everything working?

**Comment by NepNep21** [comment]
Closed due to inactivity
